### ISSUE TITLE
[Bug]: Invitation broken

### ISSUE THREAD

**Issue by tino** [heyform/heyform#121]
### Bug Description

Invite link doesn't work

### Steps to Reproduce

Note: `APP_DISABLE_REGISTRATION = 'true'`

1. Create a workspace
2. Go to Team
3. Click Invite member
4. Add email, send
5. Open email, and click link
6. Link shows login page

### Expected Behavior

Some form where you can set up your password?

### HeyForm Installation

self hosted

### Version

heyform/community-edition:latest

---

I guess this isn't supposed to work with a disabled registration? At least I don't see any code for it. But how am I supposed to invite colleagues??

**Comment by iMuFeng** [comment]
Disable registration after inviting newly registered members to join the team.

**Comment by Kurd0366** [comment]
I believe this issue is still present.

I reproduced it on the latest heyform/community-edition:latest and also on gecoit84/heyform:next-geco.

Steps:

Set APP_DISABLE_REGISTRATION=true
Invite a completely new user
Open the invitation link in an incognito window
The user is redirected to the login page instead of being able to create an account.

As a result, there is currently no way to run HeyForm in an invite-only mode. New users cannot join a workspace when public registration is disabled.

@iMuFeng Was this actually fixed? I couldn't find a related PR or commit, and the latest images still reproduce the problem.
